require 'busted.runner'()
Crimpua = require("crimp")

describe("The notation strings", function()
    describe("Given a nil value", function()
        it("returns the string with an S prefix", function()
            assert.is_equal("_", Crimpua.notation(nil))
        end)
    end)
    describe("Given a single string", function()
        it("returns the string with an S prefix", function()
            assert.is_equal("abcS", Crimpua.notation("abc"))
        end)
    end)
    describe("Given a single integer", function()
        it("returns the integer with an N prefix", function()
            assert.is_equal("1N", Crimpua.notation(1))
        end)
    end)
    describe("Given a single float", function()
        it("returns the integer with an N prefix", function()
            assert.is_equal("1.2N", Crimpua.notation(1.2))
        end)
    end)
    describe("Given a single true value", function()
        it("returns the integer with an N prefix", function()
            assert.is_equal("trueB", Crimpua.notation(true))
        end)
    end)
end)